import test from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import path from 'node:path';import {DatabaseSync} from 'node:sqlite';
test('accounts restore purchases across devices; recovery revokes sessions; guest replies stay private',async()=>{
 const dir=mkdtempSync(path.join(tmpdir(),'invitara-auth-')),origin='http://localhost:3198';const proc=spawn(process.execPath,['backend/index.mjs'],{env:{...process.env,PORT:'3198',APP_ORIGIN:origin,DATA_DIR:dir,NODE_ENV:'test'},stdio:'pipe'});let db;
 try{await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('Startup timeout')),10000);proc.stdout.on('data',d=>{if(d.toString().includes('listening')){clearTimeout(timeout);resolve();}});proc.on('error',reject);});
 const call=(url,body,cookie,method=body?'POST':'GET')=>fetch(origin+'/api'+url,{method,headers:{Origin:origin,'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},body:body?JSON.stringify(body):undefined});
 const email='host@example.test',password='a-long-test-password';const registration=await call('/auth/register',{email,password});assert.equal(registration.status,200);const account=await registration.json();assert.equal(account.recovery.length,48);
 db=new DatabaseSync(path.join(dir,'invitara.sqlite'));const p={id:'public-fixture',paid:true,published:true,expiresAt:Date.now()+60000,state:{order:["rsvp"],sections:{rsvp:{guestsMax:4}}}};db.prepare('INSERT INTO projects VALUES (?,?,?)').run(p.id,account.account.id,JSON.stringify(p));
 const login=await call('/auth/login',{email,password});assert.equal(login.status,200);const secondCookie=login.headers.getSetCookie().at(-1).split(';')[0];assert.equal((await(await call('/projects',null,secondCookie)).json()).length,1);assert.equal((await call('/projects/public-fixture/replies')).status,404);
 const reply=await call('/invites/public-fixture/rsvp',{name:'Jamie',attend:'yes',guests:2,msg:'Vegetarian please'});assert.equal(reply.status,200);const guestCookie=reply.headers.getSetCookie().at(-1).split(';')[0];assert.equal((await call('/invites/public-fixture/rsvp',{name:'Jamie',attend:'yes',guests:3,msg:'Updated'},guestCookie)).status,200);const replies=await(await call('/projects/public-fixture/replies',null,secondCookie)).json();assert.equal(replies.length,1);assert.equal(replies[0].guests,3);
 assert.equal((await call('/invites/public-fixture/rsvp',{name:'Jamie',attend:'yes',guests:90},guestCookie)).status,400);
 const recovered=await call('/auth/recover',{email,password:'new-long-password-here',recovery:account.recovery});assert.equal(recovered.status,200);assert.equal((await(await call('/me',null,secondCookie)).json()).account,null);assert.equal((await call('/auth/recover',{email,password,recovery:account.recovery})).status,401);assert.equal((await call('/auth/login',{email,password})).status,401);
 p.expiresAt=Date.now()-1;db.prepare('UPDATE projects SET body=? WHERE id=?').run(JSON.stringify(p),p.id);assert.equal((await call('/invites/public-fixture/rsvp',{name:'Jamie',attend:'yes',guests:1},guestCookie)).status,403);
 }finally{db?.close();proc.kill();await new Promise(r=>proc.once('exit',r));if(path.dirname(dir)!==path.resolve(tmpdir())||!path.basename(dir).startsWith('invitara-auth-'))throw Error('Unsafe cleanup');rmSync(dir,{recursive:true,force:true});}
});
