import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdirSync} from 'node:fs';
const origin=process.env.TEST_ORIGIN||'http://localhost:3000';
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const errors=[],missing=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().startsWith(origin)&&r.status()===404)missing.push(r.url());});mkdirSync('artifacts',{recursive:true});
try{
 await page.goto(origin+'/design.html?id=wedding-luxury-book');await page.locator('#detail-preview .nx-book').waitFor();await page.locator('#detail-preview .nx-section-hero a').click();await page.locator('.nx-book-open').waitFor();await page.getByRole('button',{name:'Next page',exact:true}).click();await page.getByRole('button',{name:'Cover',exact:true}).click();await page.locator('.nx-book-closed').waitFor();
 for(const width of [320,375,390,414,768,1024,1280,1440,1920]){await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Detail overflow '+width);}
 await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'artifacts/platform-book-preview.png'});await page.locator('#detail-use').click();await page.locator('#canvas .nx').waitFor();assert.equal(await page.locator('#canvas .nx-section').count(),9);
 const name=()=>page.locator('#canvas [data-field="basics.nameA"]').first();await name().click();await page.locator('#visual-text-content').fill('Avery');await page.locator('#save-btn').click();await page.reload();assert.equal(await name().textContent(),'Avery');
 await page.locator('#tab-design').click();await page.locator('#theme-background').fill('#f2eee2');await page.locator('#theme-background').dispatchEvent('change');await page.locator('#theme-headingSize').selectOption('72px');await page.locator('#theme-motion').selectOption('none');await page.locator('#save-btn').click();await page.reload();assert.equal(await page.evaluate(()=>window.EVER_EDITOR.getState().theme.background),'#f2eee2');assert.equal(await page.evaluate(()=>window.EVER_EDITOR.getState().theme.headingSize),'72px');
 await name().click();await page.locator('#visual-font-size').fill('48');await page.screenshot({path:'artifacts/platform-editor-desktop.png'});await page.locator('#full-preview-btn').click();await page.locator('#canvas .nx-section-hero a').click();await page.locator('#canvas .nx-book-open').waitFor();await page.getByRole('button',{name:'Next page',exact:true}).click();await page.locator('#full-preview-btn').click();
 await page.setViewportSize({width:390,height:844});await name().click();await page.locator('#visual-text-content').fill('Avery Rose');await page.locator('#save-btn').click();await page.screenshot({path:'artifacts/platform-editor-mobile.png'});assert.equal(await page.evaluate(()=>window.EVER_EDITOR.getState().basics.nameA),'Avery Rose');
 for(const width of [320,375,390,414,768,1024,1280,1440,1920]){await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Editor overflow '+width);}
 await page.goto(origin+'/create.html');const templates=await page.evaluate(()=>window.EVER_THEMES.filter(t=>t.layout==='platform'&&!t.artDirection).map(t=>({id:t.id,experience:t.experience})));assert.ok(templates.length>=40);const engines=[...new Set(templates.map(t=>t.experience))];assert.equal(engines.length,8);
 for(const engine of engines){const id=templates.find(t=>t.experience===engine).id;await page.goto(origin+'/demo.html?id='+id);await page.locator('.nx').waitFor();if(engine==='book')await page.locator('.nx-section-hero a').click();for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});if(width>=768)await page.locator('[data-width="'+(width===768?'tablet':'desktop')+'"]').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth||document.querySelector('.nx').scrollWidth>document.querySelector('.nx').clientWidth+1),false,engine+' overflow '+width);}if(engine==='gallery'){await page.locator('.nx-gallery-photo').first().click();await page.locator('.nx-lightbox[open]').waitFor();await page.getByRole('button',{name:'Next photograph'}).click();assert.match(await page.locator('.nx-lightbox p').textContent(),/^2 \/ 3/);await page.getByRole('button',{name:'Close gallery'}).click();}if(engine==='reveal'){await page.getByRole('button',{name:'Reveal the next chapter ↓'}).first().click();}}
 await page.goto(origin+'/create.html');for(const width of [320,375,390,414,768,1024,1280,1440,1920]){await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Catalogue overflow '+width);}await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'artifacts/platform-catalogue.png'});
 assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);console.log('Passed: '+templates.length+' new designs, 8 engines, Wedding → Luxury → Book → editor, persistence, global theme, mobile inspector, gallery, and 9 responsive widths.');
}finally{await browser.close();}
