import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdirSync,mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
const origin='http://localhost:3212',child=spawn(process.execPath,['backend/index.mjs'],{windowsHide:true,env:{...process.env,PORT:'3212',APP_ORIGIN:origin,DATA_DIR:mkdtempSync(path.join(tmpdir(),'invitara-premium-'))},stdio:'pipe'});let browser;
try{
 await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Startup timed out')),20000);child.stdout.on('data',d=>{if(d.toString().includes('listening')){clearTimeout(timer);resolve();}});child.on('error',reject);});
 browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[],missing=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().startsWith(origin)&&r.status()>=400)missing.push(r.url()+' '+r.status());});mkdirSync('artifacts/premium',{recursive:true});
 await page.goto(origin+'/create.html?collection=premium');await page.locator('.premium-card').first().waitFor();assert.equal(await page.locator('.premium-card').count(),5);
 await page.screenshot({path:'artifacts/premium/collection.png',fullPage:true});
 const themes=await page.evaluate(()=>window.INVITARA_availableTemplates().filter(t=>t.premium).map(t=>t.id));assert.equal(themes.length,5);
 for(const id of themes){
  await page.goto(origin+'/demo.html?id='+id);await page.locator('.suite-opening-button').click();await page.locator('.suite-open').waitFor();
  for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:1000});if(width>=768)await page.locator('[data-width="'+(width===768?'tablet':'desktop')+'"]').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,id+' horizontal overflow '+width);assert.ok(await page.locator('.suite-names').isVisible());}
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/premium/'+id+'-mobile.png',fullPage:true});
  await page.locator('.suite-reply-card summary').click();await page.locator('[name=name]').fill('Preview Guest');await page.locator('[name=attend]').selectOption('yes');await page.locator('[name=dietary]').fill('No nuts');await page.locator('[name=accommodation]').selectOption('yes');await page.locator('.ws-rsvp-form button[type=submit]').click();assert.match(await page.locator('.ex-form-note').textContent(),/Preview only/);
  await page.locator('.nx-gallery-photo').first().click();await page.getByRole('button',{name:'Next photograph',exact:true}).click();assert.match(await page.locator('.suite-lightbox p').textContent(),/^2 /);await page.getByRole('button',{name:'Close gallery',exact:true}).click();
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'Add to calendar',exact:true}).click();assert.equal((await download).suggestedFilename(),'celebration.ics');
  await page.getByRole('button',{name:/Music off/}).click();await page.waitForFunction(()=>document.querySelector('.suite-music')?.getAttribute('aria-pressed')==='true');await page.getByRole('button',{name:/Music on/}).click();
 }
 await page.goto(origin+'/create.html?collection=premium');await page.getByRole('button',{name:'Interactive preview of NOIR',exact:true}).click();await page.locator('.premium-showroom').waitFor();await page.getByRole('button',{name:'Scratch',exact:true}).click();await page.getByRole('button',{name:'Tap to reveal',exact:true}).click();await page.getByRole('button',{name:'Explore this template',exact:false}).click();await page.locator('.premium-showroom .suite-hero').waitFor();await page.getByRole('button',{name:'Next template',exact:true}).click();assert.match(await page.locator('.showroom-name').textContent(),/AURELIA/);await page.keyboard.press('Escape');assert.equal(await page.locator('.premium-showroom').count(),0);
 await page.goto(origin+'/design.html?id=premium-voyage');await page.locator('#detail-use').click();await page.locator('#canvas .suite').waitFor();await page.locator('#canvas [data-field="basics.nameA"]').first().click();await page.locator('#visual-text-content').fill('Avery');await page.locator('#save-btn').click();await page.reload();assert.equal(await page.locator('#canvas [data-field="basics.nameA"]').first().textContent(),'Avery');
 await page.emulateMedia({reducedMotion:'no-preference'});await page.goto(origin+'/demo.html?id=premium-noir');await page.locator('.suite-opening-button').click();await page.locator('.suite-open').waitFor();await page.waitForTimeout(2500);assert.equal(await page.locator('.suite-name').first().evaluate(n=>getComputedStyle(n).opacity),'1');await page.getByRole('button',{name:'Pause motion',exact:true}).click();
 await page.goto(origin+'/demo.html?id=premium-velvet');const handle=page.locator('.suite-drag-handle');await handle.scrollIntoViewIfNeeded();const box=await handle.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+170,box.y+box.height/2,{steps:15});await page.mouse.up();await page.locator('.suite-open').waitFor();
 await page.goto(origin+'/demo.html?id=premium-aurelia');await page.locator('.suite-scroll-opening').waitFor();await page.evaluate(()=>{document.querySelector('.demo-scroll').scrollTop=600;window.scrollTo(0,600);});await page.waitForTimeout(100);assert.ok(Number(await page.locator('.suite-opening').evaluate(n=>n.style.getPropertyValue('--open-progress')))>0);await page.locator('.suite-opening-button').click();await page.locator('.suite-open').waitFor();
 assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);console.log('Passed: 5 designs, 4 widths, showroom/scratch fallback, gallery, calendar, music, RSVP preview, editor save, animated tap/drag/scroll, no missing assets or browser errors.');
}finally{await browser?.close();child.kill();}
